# Dockerfile para auth-api
FROM golang:1.20-bullseye AS builder
WORKDIR /src
COPY go.mod ./
COPY go.sum ./
RUN go mod download
COPY . .
RUN go build -o auth-api .

FROM debian:bullseye-slim
WORKDIR /app
COPY --from=builder /src/auth-api .
EXPOSE 8000
CMD ["./auth-api"]